@AlignTech.WebAPI.DataFirst_HostAddress = https://localhost:7123



GET {{AlignTech.WebAPI.DataFirst_HostAddress}}/api/products

###

@id=P204
GET {{AlignTech.WebAPI.DataFirst_HostAddress}}/api/products/{{id}}

###

POST {{AlignTech.WebAPI.DataFirst_HostAddress}}/api/products
Content-Type: application/json

{
  "productId": "P204",
  "productName": "Product P204",
  "categoryId": 3,
  "price": 100,
  "quantityAvailable": 1000
}

###
